global.north_temp=1;
view_angle[1]=180;
object_set_sprite( obj_che, spr_che_2);
object_set_sprite(obj_bing, spr_bing_2);
object_set_sprite( obj_jiang, spr_jiang_2);
object_set_sprite( obj_ma, spr_ma_2);
object_set_sprite( obj_pao, spr_pao_2);
object_set_sprite( obj_shi, spr_shi_2);
object_set_sprite( obj_renshi, spr_renshi_2);
object_set_sprite( obj_shuai, spr_shuai_2);
object_set_sprite( obj_xiang, spr_xiang_2);
object_set_sprite( obj_mumu, spr_mumu_2);
object_set_sprite( obj_zu, spr_zu_2);
